# This workflow will build and test a node.js application for PR verification
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
name: client - build & test

on:
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: "14.x" # set this to the node version to use

jobs:
  build-and-test-angular:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          # Build and test the project
          cd client
          npm install
          npm run build --if-present
        # npm run test --if-present

  build-and-test-vue:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          # Build and test the project
          cd vue-client
          npm install
          npm run build --if-present
          npm run test:unit --if-present
          npm run test:e2e:ci --if-present
